# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [1]:
#Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]  # this is an list type 
array_list = np.array(object = list_) #this is numpy array type
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [2]:
print("Data type of each element in list_: ")
for i in list_ :
    print(type(i))
print("\nData type of each element in array_list:")
for i in array_list :
    print(type(i))

Data type of each element in list_: 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:
###  array_list = np.array(object = list_, dtype = int)
###  Will there be any difference in the data type of the elements present in both the variables, list_ and  arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.


In [3]:
list_ = [ '1' , '2' , '3' , '4' , '5' ] 
array_list = np.array(object = list_)

array_list = np.array(object = list_, dtype = int)
for i in array_list:
    print(type(i))
for i in list_:
    print(type(i))
    

# the changes will be only takes places in the array_list that the string values is changes into the int values but values of list remains the same

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


###  Consider the below code to answer further questions:
import numpy as np list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ] array_list = np.array(object = list_)
# Q4. Write a code to find the following characteristics of variable, num_array: 
# (i) shape 
# (ii) size 


In [7]:
import numpy as np 
list_ = [ '1' , '2' , '3' , '4' , '5' ]  
array_list = np.array(object = list_)
# (i) Shape
print("Shape of array_list:", array_list.shape)
print("size of list_:", array_list.size)

Shape of array_list: (5,)
size of list_: 5


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function. 
[Hint: The size of the array will be 9 and the shape will be (3,3).] 

In [5]:
import numpy as np
ar = np.zeros((3,3))
print(f' the shape of array is {ar.shape}')
print(f'the size of array is {ar.size}')
print(ar)

 the shape of array is (3, 3)
the size of array is 9
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [6]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
